--Generated By msgid-gen-lua Do not Edit
pb = require 'pb'
protoc = require "Framework/Net/lua-protobuf/protoc"
serpent = require "Framework/Net/lua-protobuf/serpent"

local pbfiles = {
	'test.pb',
	'TaskService.pb',
	'logic.pb',
}
local loadpb = function ()
	local pbpath = CS.LuaFramework.Util.LuaDataPath .. CS.LuaFramework.AppConst.LuaTempDir .. "Net/Protol/"
	-- 载入编译的pb文件
	for i=1,#pbfiles do
		local fullname = pbpath..pbfiles[i]
		assert(pb.loadfile(fullname)) 
		print('load pb file:'..fullname)
	end

end

loadpb()

return protoMsg