// Code generated by protogen.
// DO NOT EDIT!!!
// source:  logic.proto
//
using CitrusNet;
using CitrusNet.Phobos;
using System.Collections.Generic;

namespace logic.proto {
    // 推送协议需要id
    [ProtoBuf.ProtoContract]
    public enum EMsgIds {
        
        ECS_Player_Login = 101,
        
        ESC_Player_Login = 103,
        
        ECS_Player_Tick = 104,
        
        ESC_Player_Tick = 105,
        
        ECS_Player_AddCoin = 106,
        
        ESC_Player_AddCoin = 107,
        
        ECS_Player_Test = 108,
        
        ESC_Player_Test = 109,
        // 聊天协议
        ECS_Chat_Join = 112,
        
        ESC_Chat_Join = 113,
        
        ECS_Chat_Leave = 114,
        
        ESC_Chat_Leave = 115,
        
        ECS_Chat_Talk = 116,
        
        ESC_Chat_Talk = 117,
        // 工会协议
        ECS_Guide_Create = 118,
        
        ESC_Guide_Create = 119,
        
        ECS_Guide_Join = 120,
        
        ESC_Guide_Join = 121,
        
        ECS_Guide_Leave = 122,
        
        ESC_Guide_Leave = 123,
        
        ECS_Guide_Contribute = 124,
        
        ESC_Guide_Contribute = 125,
    }


    
    [ProtoBuf.ProtoContract]
    public class CS_Player_Tick : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string msg { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class SC_Player_Tick : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string msg { get; set; }
    }

    // 登录
    [ProtoBuf.ProtoContract]
    public class CS_Player_Login : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string token { get; set; }
    }

    // 登录返回
    [ProtoBuf.ProtoContract]
    public class SC_Player_Login : NetCommand {
        // 防止大数传输异常,这里直接用字符
        [ProtoBuf.ProtoMember(1)]
        public string id { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class CS_Player_Test : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string msg { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class SC_Player_Test : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string msg { get; set; }
        
        [ProtoBuf.ProtoMember(2)]
        public string date { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class CS_Player_AddCoin : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public int coin { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class SC_Player_AddCoin : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public int coin { get; set; }
    }

    // 聊天协议
    [ProtoBuf.ProtoContract]
    public class CS_Chat_Join : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string playerName { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class SC_Chat_Join : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public int code { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class CS_Chat_Leave : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string playerName { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class SC_Chat_Leave : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public int code { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class CS_Chat_Talk : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string msg { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class SC_Chat_Talk : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public int code { get; set; }
        
        [ProtoBuf.ProtoMember(2)]
        public string from { get; set; }
        
        [ProtoBuf.ProtoMember(3)]
        public string msg { get; set; }
    }

    // 工会协议
    [ProtoBuf.ProtoContract]
    public class CS_Guide_Create : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string guideName { get; set; }
        
        [ProtoBuf.ProtoMember(2)]
        public string player { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class SC_Guide_Create : NetCommand {
    }

    
    [ProtoBuf.ProtoContract]
    public class CS_Guide_Join : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string player { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class SC_Guide_Join : NetCommand {
    }

    
    [ProtoBuf.ProtoContract]
    public class CS_Guide_Leave : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public string player { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class SC_Guide_Leave : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public int code { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class CS_Guide_Contribute : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public int coin { get; set; }
    }

    
    [ProtoBuf.ProtoContract]
    public class SC_Guide_Contribute : NetCommand {
        
        [ProtoBuf.ProtoMember(1)]
        public int code { get; set; }
    }


}